[toolchain]
channel = "nightly"
profile = "minimal"
components = [
  "cargo",
  "clippy",
  "llvm-tools-preview",
  "rust-analyzer",
  "rust-src",
  "rustfmt",
]
targets = [
  "wasm32-unknown-unknown",
  "x86_64-unknown-linux-musl",
  "aarch64-unknown-linux-gnu",
]
