{
  lib,
  pkgs,
  repoRoot,
}:
let
  managedCargoLib = import "${repoRoot}/modules/managed-cargo/lib.nix" {
    inherit pkgs lib;
  };
  managedCargoModule = import "${repoRoot}/modules/managed-cargo/default.nix";
  fixturesDir = "${toString repoRoot}/tests/fixtures/managed-cargo";
  fixturePath = name: "${fixturesDir}/${name}";
  readToml = path: builtins.fromTOML (builtins.readFile path);

  supportOptionsModule =
    { lib, ... }:
    {
      options = {
        assertions = lib.mkOption {
          type = lib.types.listOf (
            lib.types.submodule {
              options = {
                assertion = lib.mkOption { type = lib.types.bool; };
                message = lib.mkOption { type = lib.types.str; };
              };
            }
          );
          default = [ ];
        };

        devenv.root = lib.mkOption { type = lib.types.str; };

        files = lib.mkOption {
          type = lib.types.attrsOf (
            lib.types.submodule {
              options.source = lib.mkOption { type = lib.types.path; };
            }
          );
          default = { };
        };

        outputs = lib.mkOption {
          type = lib.types.attrsOf lib.types.anything;
          default = { };
        };
      };
    };

  evalManagedCargo =
    {
      root,
      catalogPath ? "Cargo.catalog.toml",
      specPath ? "Cargo.poly.toml",
      sourcePath ? ".",
      outputPath ? "Cargo.toml",
      inputs ? { },
    }:
    lib.evalModules {
      modules = [
        managedCargoModule
        supportOptionsModule
        {
          _module.args = {
            inherit pkgs inputs;
          };
        }
        {
          devenv.root = root;
          rustEnv.managedCargo = {
            enable = true;
            inherit
              catalogPath
              specPath
              sourcePath
              outputPath
              ;
          };
        }
      ];
    };

  helperOutputs =
    derivationNamePrefix:
    managedCargoLib.mkManagedCargoOutputs {
      catalogPath = fixturePath "helper-project/Cargo.catalog.toml";
      specPath = fixturePath "helper-project/Cargo.poly.toml";
      sourcePath = fixturePath "helper-project";
      inherit derivationNamePrefix;
    };
in
{
  managedCargo."test helper merges catalog versions features and passthrough deps" = {
    expr =
      let
        outputs = helperOutputs "managed-cargo-helper-merge";
        manifest = readToml outputs.cargoManifest;
      in
      manifest.package.name == "helper-fixture"
      && manifest.dependencies.demo.version == "1.2.3"
      &&
        manifest.dependencies.demo.features == [
          "catalog-feature"
          "spec-feature"
        ]
      && manifest.dependencies.path_dep.path == "./vendor/path-dep"
      && !(manifest.dependencies.path_dep ? version)
      && manifest.dependencies.git_dep.git == "https://example.com/git-dep.git"
      && !(manifest.dependencies.git_dep ? version)
      && manifest."dev-dependencies".test_only.version == "0.0.5";
    expected = true;
  };

  managedCargo."test helper cargoSourceTree replaces stale manifest and preserves source files" = {
    expr =
      let
        outputs = helperOutputs "managed-cargo-helper-source-tree";
        manifestText = builtins.readFile "${outputs.cargoSourceTree}/Cargo.toml";
        manifest = builtins.fromTOML manifestText;
        srcText = builtins.readFile "${outputs.cargoSourceTree}/src/lib.rs";
      in
      !(lib.hasInfix "stale-manifest" manifestText)
      && manifest.package.name == "helper-fixture"
      && builtins.pathExists "${outputs.cargoSourceTree}/src/lib.rs"
      && lib.hasInfix "pub fn fixture()" srcText
      && lib.hasInfix "\"ok\"" srcText;
    expected = true;
  };

  managedCargo."test helper surfaces missing catalog dependencies" = {
    expr =
      let
        outputs = managedCargoLib.mkManagedCargoOutputs {
          catalogPath = fixturePath "missing-dependency/Cargo.catalog.toml";
          specPath = fixturePath "missing-dependency/Cargo.poly.toml";
          sourcePath = fixturePath "missing-dependency";
          derivationNamePrefix = "managed-cargo-helper-missing-dep";
        };
      in
      builtins.readFile outputs.cargoManifest;
    expectedError.type = "Error";
    expectedError.msg = ".*dependency 'missing_dep' is missing from the shared catalog.*";
  };

  managedCargo."test module materializes managed Cargo manifest with devenv header" = {
    expr =
      let
        root = fixturePath "module-project";
        result = evalManagedCargo { inherit root; };
        manifestText = builtins.readFile result.config.outputs.cargo_manifest;
        manifest = builtins.fromTOML manifestText;
      in
      lib.hasPrefix "# GENERATED BY DEVENV: DO NOT EDIT DIRECTLY" manifestText
      && lib.hasInfix "${root}/Cargo.poly.toml" manifestText
      && result.config.files."Cargo.toml".source == result.config.outputs.cargo_manifest
      && manifest.package.name == "module-fixture"
      &&
        manifest.dependencies.demo.features == [
          "catalog-feature"
          "spec-feature"
        ];
    expected = true;
  };

  managedCargo."test module keeps outputs when outputPath is null" = {
    expr =
      let
        result = evalManagedCargo {
          root = fixturePath "module-project";
          outputPath = null;
        };
      in
      result.config.outputs ? cargo_manifest
      && result.config.outputs ? cargo_source_tree
      && result.config.files == { };
    expected = true;
  };

  managedCargo."test module skips materialization for external spec paths but still builds outputs" =
    {
      expr =
        let
          externalRoot = fixturePath "external-project";
          result = evalManagedCargo {
            root = fixturePath "module-project";
            catalogPath = "${externalRoot}/Cargo.catalog.toml";
            specPath = "${externalRoot}/Cargo.poly.toml";
            sourcePath = externalRoot;
          };
          manifest = readToml result.config.outputs.cargo_manifest;
        in
        manifest.package.name == "external-fixture" && result.config.files == { };
      expected = true;
    };
}
