{
  pkgs,
  config,
  lib,
  inputs ? { },
  ...
}:

let
  cfg = config.rustEnv.managedCargo;
  managedCargoEnabled = cfg.enable;
  managedCargoLib = import ./lib.nix {
    inherit pkgs lib;
  };
  editablePaths = import ./editable-paths.nix {
    inherit config inputs lib;
  };
  resolveFromRoot = path: if lib.hasPrefix "/" path then path else "${config.devenv.root}/${path}";
  pathIsInsideRoot =
    path:
    let
      root = toString config.devenv.root;
      rootPrefix = "${root}/";
    in
    path == root || lib.hasPrefix rootPrefix path;
  managedCargoCatalogPath = resolveFromRoot cfg.catalogPath;
  managedCargoSpecPath = resolveFromRoot cfg.specPath;
  managedCargoCatalogEditPath = editablePaths.editablePathFor managedCargoCatalogPath;
  managedCargoSpecEditPath = editablePaths.editablePathFor managedCargoSpecPath;
  managedCargoHeader = ''
    # GENERATED BY DEVENV: DO NOT EDIT DIRECTLY
    #
    # Project-local manifest and dependency settings (no version numbers): `${managedCargoSpecEditPath}`
    # To add globally managed crates (with version numbers):
    # - check latest crate releases using `cargo info`
    # - add to the shared AgentRoots catalog source of truth, edit: `${managedCargoCatalogEditPath}`
    # - refresh nix store symlinks in local project: `devenv shell --nu-tui --no-eval-cache --refresh-eval-cache true`
    #
  '';
  managedCargoSourcePath = resolveFromRoot (
    if cfg.sourcePath != null then cfg.sourcePath else dirOf cfg.specPath
  );
  managedCargoShouldMaterialize =
    managedCargoEnabled && cfg.outputPath != null && pathIsInsideRoot managedCargoSpecPath;
  managedCargoOutputs =
    if managedCargoEnabled then
      managedCargoLib.mkManagedCargoOutputs {
        catalogPath = managedCargoCatalogPath;
        specPath = managedCargoSpecPath;
        sourcePath = managedCargoSourcePath;
        header = managedCargoHeader;
      }
    else
      null;
in
{
  options.rustEnv.managedCargo = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Generate Cargo.toml from a repo-owned Cargo.poly.toml and a shared crate version catalog.";
    };

    catalogPath = lib.mkOption {
      type = lib.types.str;
      default = toString ./Cargo.catalog.toml;
      description = "Path to the shared crate version catalog TOML.";
    };

    specPath = lib.mkOption {
      type = lib.types.str;
      default = "Cargo.poly.toml";
      description = "Repo-owned Cargo manifest spec TOML without crates.io versions.";
    };

    outputPath = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = "Cargo.toml";
      description = "Output path for the generated Cargo manifest. Set to null to disable workspace materialization and expose only outputs.cargo_manifest.";
    };

    sourcePath = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      description = "Repo source root used for outputs.cargo_source_tree. Defaults to the directory containing specPath.";
    };
  };

  config = lib.mkMerge [
    {
      assertions = lib.optionals managedCargoEnabled [
        {
          assertion = builtins.pathExists managedCargoSpecPath;
          message = "rustEnv.managedCargo.enable is true but specPath does not exist: ${managedCargoSpecPath}";
        }
        {
          assertion = builtins.pathExists managedCargoSourcePath;
          message = "rustEnv.managedCargo.enable is true but sourcePath does not exist: ${managedCargoSourcePath}";
        }
      ];

      outputs = lib.mkIf managedCargoEnabled {
        cargo_manifest = managedCargoOutputs.cargoManifest;
        cargo_source_tree = managedCargoOutputs.cargoSourceTree;
        rust_deps_catalog = managedCargoOutputs.rustDepsCatalog;
      };
    }
    (lib.mkIf managedCargoShouldMaterialize {
      files."${cfg.outputPath}".source = managedCargoOutputs.cargoManifest;
    })
  ];
}
